services:
          h2:
            image: oscarfonts/h2
            container_name: h2
            environment:
              - H2_OPTIONS=-ifNotExists
              - H2_TCP_PORT=9092
              - H2_WEB_PORT=8082
              - H2_BASE_DIR=/opt/h2-data
            ports:
              - 9092:8082

          backend:
            image: antoniorodenas/backend:latest
            container_name: backend
            build:
              context: ./backend
            ports:
              - 8080:8080
            depends_on:
              - h2

          frontend:
            image: antoniorodenas/frontend:latest
            container_name: frontend
            build:
              context: ./frontend
            ports:
              - 80:80
            depends_on:
              - backend
